export const SET_LANGUAGE_TO_EN = "SET_LANGUAGE_TO_EN";
export const SET_LANGUAGE_TO_DE = "SET_LANGUAGE_TO_DE";

export const CHANGE_EXPERIENCE = "CHANGE_EXPERIENCE";
export const SET_ACTIVE_EXPERIENCE = "SET_ACTIVE_EXPERIENCE";
export const SET_EVENTS = "SET_EVENTS";
export const SET_NEWS = "SET_NEWS";
export const SET_EXHIBITIONS = "SET_EXHIBITIONS";
export const SET_RESOURCE_GENRES = "SET_RESOURCE_GENRES";

export const SET_PARTICIPANTS = "SET_PARTICIPANTS";
export const SET_PAGES = "SET_PAGES";
export const SET_VENUES = "SET_VENUES";
export const SET_DOCUMENTS = "SET_DOCUMENTS";
export const SET_RESOURCES = "SET_RESOURCES";
export const SET_CALENDAR_ITEMS = "SET_CALENDAR_ITEMS";
export const SET_CALENDAR = "SET_CALENDAR";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const INCREASE_EXPERIENCE_TRANSITION = "INCREASE_EXPERIENCE_TRANSITION";
export const DECREASE_EXPERIENCE_TRANSITION = "DECREASE_EXPERIENCE_TRANSITION";
export const SET_IS_VISIBLE_TO_TRUE = "SET_IS_VISIBLE_TO_TRUE";
export const IS_LOADED = "IS_LOADED";
export const HAS_AGREED_TO_TERMS = "HAS_AGREED_TO_TERMS";
export const SET_NAVBAR_ITEMS = "SET_NAVBAR_ITEMS";