export const SET_LANGUAGE_TO_EN = "SET_LANGUAGE_TO_EN";
export const SET_LANGUAGE_TO_DE = "SET_LANGUAGE_TO_DE";

export const CHANGE_EXPERIENCE = "CHANGE_EXPERIENCE";


export const SET_EVENTS = "SET_EVENTS";
export const SET_NEWS = "SET_NEWS";
export const SET_EXHIBITIONS = "SET_EXHIBITIONS";
export const SET_PARTICIPANTS = "SET_PARTICIPANTS";
export const SET_VENUES = "SET_VENUES";
export const SET_DOCUMENTS = "SET_DOCUMENTS";


export const IS_LOADED = "IS_LOADED";